name: Monthly contributor report
on:
  workflow_dispatch:
    inputs:
      start_date:
        type: string
        description: |
          Custom start date for metrics generation in YYYY-MM-DD format.
        required: true
      end_date:
        type: string
        description: |
          Custom end date for metrics generation in YYYY-MM-DD format.
        required: true
  # Run on every 22th of the month. This guarantees that this action runs
  # before the Dev Sync (every 4th Tuesday of the month in the afternoon).
  schedule:
    - cron: '0 0 22 * *'

permissions:
  issues: write

jobs:
  contributor_report:
    name: contributor report
    runs-on: ubuntu-latest

    steps:
      - name: Set the start and end dates
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{inputs.start_date}}" && -n "${{inputs.end_date}}" ]] ; then
            start_date="${{inputs.start_date}}"
            end_date=${{inputs.end_date}}
          else
            start_date=$(date -d "last month" +%Y-%m-%d)
            end_date=$(date -d "yesterday" +%Y-%m-%d)
          fi

          echo "START_DATE=$start_date" >> "$GITHUB_ENV"
          echo "END_DATE=$end_date" >> "$GITHUB_ENV"
  
      - name: Collect contributor metrics
        uses: github/contributors@v1
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
          START_DATE: ${{ env.START_DATE }}
          END_DATE: ${{ env.END_DATE }}
          # We explicitly list repos for our metrics here so temporary forks like
          #  e.g. systemd, gentoo, or udev don't pollute the stats
          REPOSITORY: "flatcar/nebraska,flatcar/flatcar-website,flatcar/flatcar-build-scripts,flatcar/baselayout,flatcar/bootengine,flatcar/coreos-cloudinit,flatcar/flatcar-dev-util,flatcar/init,flatcar/locksmith,flatcar/mantle,flatcar/mayday,flatcar/nss-altfiles,flatcar/scripts,flatcar/seismograph,flatcar/shim,flatcar/sysroot-wrappers,flatcar/toolbox,flatcar/torcx,flatcar/update-ssh-keys,flatcar/update_engine,flatcar/updateservicectl,flatcar/Flatcar,flatcar/flatcar-packer-qemu,flatcar/flatcar-ipxe-scripts,flatcar/flatcar-cloud-image-uploader,flatcar/flatcar-linux-update-operator,flatcar/flatcar-release-mirror,flatcar/flatcar-terraform,flatcar/sdnotify-proxy,flatcar/flatcar-automation,flatcar/nebraska-update-agent,flatcar/fleetlock,flatcar/flog,flatcar/ign-converter,flatcar/nomad-on-flatcar,flatcar/sysext-bakery,flatcar/reports,flatcar/flatcar-demos,flatcar/jitsi-server,flatcar/flatcar-mastodon,flatcar/ue-rs,flatcar/azure-marketplace-ingestion-api"
          SPONSOR_INFO: "false"

      - name: New PRs opened (and still open) metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'org:flatcar is:pr is:open -author:flatcar-infra created:${{ env.START_DATE }}..${{ env.END_DATE }}'
            # "time to answer" only supported for discussions
            HIDE_TIME_TO_ANSWER: true
            # This metric measures items that are still open
            HIDE_TIME_TO_CLOSE: true
            IGNORE_USERS: "flatcar-infra,github-actions[bot],dependabot[bot]"

      - name: rename new PRs metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md prs_opened.md

      - name: PRs closed metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'org:flatcar is:pr -author:flatcar-infra closed:${{ env.START_DATE }}..${{ env.END_DATE }}'
            # "time to answer" only supported for discussions
            HIDE_TIME_TO_ANSWER: true
            IGNORE_USERS: "flatcar-infra,github-actions[bot],dependabot[bot]"

      - name: rename closed PRs metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md prs_closed.md

      - name: Total open PRs metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'org:flatcar is:pr is:open -author:flatcar-infra'
            # "time to answer" only supported for discussions
            HIDE_TIME_TO_ANSWER: true
            # This metric measures items that are still open
            HIDE_TIME_TO_CLOSE: true
            IGNORE_USERS: "flatcar-infra,github-actions[bot],dependabot[bot]"

      - name: rename open PR metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md prs_open.md
  
      - name: Collect discussion metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'repo:flatcar/Flatcar type:discussions created:${{ env.START_DATE }}..${{ env.END_DATE }}'

      - name: rename discussion metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md discussion_metrics.md

      - name: New issues opened (and still open) metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'org:flatcar is:issue is:open created:${{ env.START_DATE }}..${{ env.END_DATE }}'
            # "time to answer" only supported for discussions
            HIDE_TIME_TO_ANSWER: true
            # This metric measures items that are still open
            HIDE_TIME_TO_CLOSE: true
            IGNORE_USERS: "flatcar-infra,github-actions[bot],dependabot[bot]"

      - name: rename new issues opened metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md issues_opened.md

      - name: Issues closed metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'org:flatcar is:issue closed:${{ env.START_DATE }}..${{ env.END_DATE }}'
            # "time to answer" only supported for discussions
            HIDE_TIME_TO_ANSWER: true
            IGNORE_USERS: "flatcar-infra,github-actions[bot],dependabot[bot]"

      - name: rename issues closed metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md issues_closed.md
  
      - name: Total open Issues metrics
        uses: github/issue-metrics@v2
        env:
            GH_TOKEN: ${{ secrets.GH_ACTION_METRICS_ORG_READ }}
            SEARCH_QUERY: 'org:flatcar is:issue is:open'
            # "time to answer" only supported for discussions
            HIDE_TIME_TO_ANSWER: true
            # This metric measures items that are still open
            HIDE_TIME_TO_CLOSE: true
            IGNORE_USERS: "flatcar-infra,github-actions[bot],dependabot[bot]"

      - name: rename issues closed metrics file
        shell: bash
        run: |
          set -euo pipefail
          mv issue_metrics.md issues_open.md
  
      - name: Upload individual reports
        uses: actions/upload-artifact@v3
        with:
          retention-days: 32
          name: raw-reports
          path: |
            ./*.md

      - name: Assemble full report
        shell: bash
        run: |
          set -euo pipefail

          cat contributors.md > report.md

          echo -e "\n\n# Discussions Metrics" >> report.md
          tail --lines=+2 discussion_metrics.md >> report.md

          echo -e "\n\n# Issue Metrics" >> report.md

          echo -e "\n## Open Issues Summary" >> report.md
          # remove full issues list from stats; we only want the summary
          tail --lines=+2 issues_open.md \
              | awk '/^\| Title \| URL \| Author \|/{silent=1} {if (silent==0) print $0}' \
              >> report.md

          echo -e "\n## New Issues created (and still open)" >> report.md
          tail --lines=+2 issues_opened.md >> report.md
          echo -e "\n## Issues closed" >> report.md
          tail --lines=+2 issues_closed.md >> report.md

          echo -e "\n\n# Pull Requests Metrics" >> report.md
          echo -e "\n## Open PRs Summary" >> report.md
          # remove full PRs list from stats; we only want the summary
          tail --lines=+2 prs_open.md \
              | awk '/^\| Title \| URL \| Author \|/{silent=1} {if (silent==0) print $0}' \
              >> report.md

          echo -e "\n## New PRs created (and still open)" >> report.md
          tail --lines=+2 prs_opened.md >> report.md
          echo -e "\n## PRs closed" >> report.md
          tail --lines=+2 prs_closed.md >> report.md
  
      - name: Create issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Monthly contributions report ${{ env.START_DATE }} - ${{ env.END_DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          content-filepath: ./report.md
          labels: kind/metric
